import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  user?: { name: string; email: string; picture: string } | null;
}

export default function RootLayout({ children, user }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Header shows only if user is logged in */}
        {user && (
          <header className="border-b sticky top-0 bg-white z-50">
            <Header user={user} />
          </header>
        )}

        <div className="bg-[#F4F2ED] flex-1 w-full">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
